name: Trigger arch repo build
on:
  push:
    branches: [main]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api repos/veronoicc/vero-on-arch/dispatches \
            -f event_type=equicord_plugins_update
        env:
          GH_TOKEN: ${{ secrets.REPO_DISPATCH_TOKEN }}
